use_frameworks!

platform :ios, '11.0'

target 'ViewSizeExpansion_Example' do
  pod 'ViewSizeExpansion', :path => '../'
  pod 'SnapKit'

  target 'ViewSizeExpansion_Tests' do
    inherit! :search_paths

    
  end
end
